'use strict';
const Generator = require('yeoman-generator');
const chalk = require('chalk');
const yosay = require('yosay');

module.exports = class extends Generator {
  prompting() {
    // Have Yeoman greet the user.
    this.log(yosay(
      'Welcome to the awesome ' + chalk.red('generator-espl-angular') + ' generator!'
    ));

    const prompts = [{
      type: 'confirm',
      name: 'someAnswer',
      message: 'Would you like to enable this option?',
      default: true
    }];

    return this.prompt(prompts).then(props => {
      // To access props later use this.props.someAnswer;
      this.props = props;
    });
  }

  writing() {

    var allFileNames = [
      ".angular-cli.json",
      ".babelrc",
      ".clang-format",
      ".docker",
      ".dockerignore",
      ".editorconfig",
      ".eslintrc",
      ".gitignore",
      ".stylelintrc",
      ".travis.yml",
      "docker-compose.production.yml",
      "docker-compose.yml",
      "dummyfile.txt",
      "karma.conf.js",
      "nodemon.json",
      "package.json",
      "protractor.conf.js",
      "proxy.conf.json",
      "README.md",
      "tsconfig.json",
      "tslint.json",
      ".docker/great-big-angular2-example.development.dockerfile",
      ".docker/great-big-angular2-example.production.dockerfile",
      ".docker/nginx.conf",
      "e2e/about.e2e-spec.ts",
      "e2e/app.e2e-spec.ts",
      "e2e/app.po.ts",
      "e2e/not-found.e2e-spec.ts",
      "e2e/tsconfig.e2e.json",
      "server/auth-passport.js",
      "server/node-proxy.js",
      "server/node-server.js",
      "server/proxy-config.js",
      "server/webpack-dev-proxy.js",
      "server/db/claim.json",
      "server/db/claimRebuttal.json",
      "server/db/contact.json",
      "server/db/crisis.json",
      "server/db/hero.json",
      "server/db/note.json",
      "server/db/rebuttal.json",
      "server/db/user.json",
      "src/favicon.ico",
      "src/index.html",
      "src/main.ts",
      "src/polyfills.ts",
      "src/styles.scss",
      "src/test.ts",
      "src/tsconfig.app.json",
      "src/tsconfig.spec.json",
      "src/app/app.module.ts",
      "src/app/app.page.css",
      "src/app/app.page.html",
      "src/app/app.page.spec.ts",
      "src/app/app.page.ts",
      "src/app/app.routing.ts",
      "src/app/app.spec.ts",
      "src/app/core/core.module.ts",
      "src/app/core/core.routing.ts",
      "src/app/core/index.ts",
      "src/app/core/spinner.component.ts",
      "src/app/core/about/about.page.ts",
      "src/app/core/auth/auth.guard.ts",
      "src/app/core/auth/auth.module.ts",
      "src/app/core/auth/auth.service.ts",
      "src/app/core/auth/login/login.module.ts",
      "src/app/core/auth/login/login.routing.ts",
      "src/app/core/auth/login/login-form/login-form.component.css",
      "src/app/core/auth/login/login-form/login-form.component.html",
      "src/app/core/auth/login/login-form/login-form.component.spec.ts",
      "src/app/core/auth/login/login-form/login-form.component.ts",
      "src/app/core/interfaces/iconsole.ts",
      "src/app/core/interfaces/ilang.ts",
      "src/app/core/interfaces/index.ts",
      "src/app/core/interfaces/iwindow.ts",
      "src/app/core/navigator/layout.component.ts",
      "src/app/core/navigator/nav-item.component.ts",
      "src/app/core/navigator/navigator.module.ts",
      "src/app/core/navigator/sidenav.component.ts",
      "src/app/core/navigator/toolbar.component.ts",
      "src/app/core/not-found/not-found.page.ts",
      "src/app/core/platform/platform.directive.spec.ts",
      "src/app/core/platform/platform.directive.ts",
      "src/app/core/services/app.service.ts",
      "src/app/core/services/base.service.ts",
      "src/app/core/services/console.service.ts",
      "src/app/core/services/data.service.spec.ts",
      "src/app/core/services/data.service.ts",
      "src/app/core/services/default-request-options.service.ts",
      "src/app/core/services/exception.service.ts",
      "src/app/core/services/in-memory-data.service.ts",
      "src/app/core/services/index.ts",
      "src/app/core/services/log.service.spec.ts",
      "src/app/core/services/log.service.ts",
      "src/app/core/services/message.service.ts",
      "src/app/core/services/router-extensions.service.ts",
      "src/app/core/services/user.service.ts",
      "src/app/core/services/window.service.ts",
      "src/app/core/store/index.ts",
      "src/app/core/store/util.ts",
      "src/app/core/store/session/session.effects.ts",
      "src/app/core/store/session/session.model.ts",
      "src/app/core/store/session/session.reducer.ts",
      "src/app/core/store/slice/slice.actions.ts",
      "src/app/core/store/slice/slice.functions.ts",
      "src/app/core/utils/config.spec.ts",
      "src/app/core/utils/config.ts",
      "src/app/core/utils/index.ts",
      "src/app/core/utils/view-broker.spec.ts",
      "src/app/core/utils/view-broker.ts",
      "src/app/shared/animations.ts",
      "src/app/shared/index.ts",
      "src/app/shared/selective-preloading-strategy.ts",
      "src/app/shared/shared.module.ts",
      "src/app/shared/alert/alert.component.spec.ts",
      "src/app/shared/alert/alert.component.ts",
      "src/app/shared/alert/index.ts",
      "src/app/shared/analytics/analytics.module.ts",
      "src/app/shared/analytics/index.ts",
      "src/app/shared/analytics/services/analytics.service.spec.ts",
      "src/app/shared/analytics/services/analytics.service.ts",
      "src/app/shared/awesome/awesome.pipe.ts",
      "src/app/shared/banner/banner.component.css",
      "src/app/shared/banner/banner.component.detect-changes.spec.ts",
      "src/app/shared/banner/banner.component.html",
      "src/app/shared/banner/banner.component.spec.ts",
      "src/app/shared/banner/banner.component.ts",
      "src/app/shared/button/button.component.spec.ts",
      "src/app/shared/button/button.component.ts",
      "src/app/shared/button/index.ts",
      "src/app/shared/can-deactivate/can-deactivate.guard.ts",
      "src/app/shared/container/container.component.spec.ts",
      "src/app/shared/container/container.component.ts",
      "src/app/shared/dialog/dialog.service.ts",
      "src/app/shared/directives/ifAuthorize.directive.ts",
      "src/app/shared/draggable/draggable.directive.ts",
      "src/app/shared/form/form.component.spec.ts",
      "src/app/shared/form/form.component.ts",
      "src/app/shared/form/index.ts",
      "src/app/shared/form-error/form-error.component.spec.ts",
      "src/app/shared/form-error/form-error.component.ts",
      "src/app/shared/form-group/form-group.component.spec.ts",
      "src/app/shared/form-group/form-group.component.ts",
      "src/app/shared/highlight/highlight.directive.spec.ts",
      "src/app/shared/highlight/highlight.directive.ts",
      "src/app/shared/input/input.component.spec.ts",
      "src/app/shared/input/input.component.ts",
      "src/app/shared/label/label.component.spec.ts",
      "src/app/shared/label/label.component.ts",
      "src/app/shared/logo/index.ts",
      "src/app/shared/logo/logo.component.css",
      "src/app/shared/logo/logo.component.spec.ts",
      "src/app/shared/logo/logo.component.ts",
      "src/app/shared/modal/modal.component.css",
      "src/app/shared/modal/modal.component.spec.ts",
      "src/app/shared/modal/modal.component.ts",
      "src/app/shared/modal-content/modal-content.component.spec.ts",
      "src/app/shared/modal-content/modal-content.component.ts",
      "src/app/shared/test/browser-test-shim.js",
      "src/app/shared/test/jasmine-matchers.d.ts",
      "src/app/shared/test/jasmine-matchers.ts",
      "src/app/shared/test/router-stubs.ts",
      "src/app/shared/test/test.module.ts",
      "src/app/shared/test/util.ts",
      "src/app/shared/test/e2e/dropdowns.ts",
      "src/app/shared/test/mocks/mock-location-strategy.ts",
      "src/app/shared/test/mocks/ng2-config.mock.ts",
      "src/app/shared/test/mocks/router-extensions.mock.ts",
      "src/app/shared/test/mocks/window.mock.ts",
      "src/app/shared/test/providers/core.ts",
      "src/app/shared/test/providers/http.ts",
      "src/app/shared/test/providers/router.ts",
      "src/app/shared/test/shorthand/ng2-jasmine.ts",
      "src/app/shared/title-case/title-case.pipe.spec.ts",
      "src/app/shared/title-case/title-case.pipe.ts",
      "src/app/shared/twain/twain.component.spec.ts",
      "src/app/shared/twain/twain.component.ts",
      "src/app/shared/twain/twain.service.ts",
      "src/app/shared/welcome/welcome.component.spec.ts",
      "src/app/shared/welcome/welcome.component.ts",
      //"src/assets/bernie-app.png",
      //"src/assets/bernie-sanders-128.jpg",
      //"src/assets/bernie-spreadsheet.png",
      //"src/assets/collection.png",
      //"src/assets/counter.png",
      //"src/assets/notes.png",
      //"src/assets/question-mark.png",
      //"src/assets/rangleio-logo.svg",
      "src/assets/styles/align.css",
      "src/assets/styles/background-colors.css",
      "src/assets/styles/basscss.scss",
      "src/assets/styles/colors.css",
      "src/assets/styles/flexbox.css",
      "src/assets/styles/grid.css",
      "src/assets/styles/hero-styles.css",
      "src/assets/styles/heroes.css",
      "src/assets/styles/hide.css",
      "src/assets/styles/index.scss",
      "src/assets/styles/media-object.css",
      "src/assets/styles/position.css",
      "src/assets/styles/responsive-margin.css",
      "src/assets/styles/responsive-padding.css",
      "src/environments/environment.prod.ts",
      "src/environments/environment.ts",
      "src/modules/config.ts",
      "src/modules/patchReq.model.ts",
      "src/modules/dashboard/dashboard.module.ts",
      "src/modules/dashboard/dashboard.routing.ts",
      "src/modules/dashboard/components/dashboard.component.css",
      "src/modules/dashboard/components/dashboard.component.html",
      "src/modules/dashboard/components/dashboard.component.ts",
      "src/modules/dashboard/services/dashboard.service.ts",
      "src/modules/dashboard/store/dashboard.actions.ts",
      "src/modules/dashboard/store/dashboard.effects.ts",
      "src/modules/dashboard/store/dashboard.model.ts",
      "src/modules/dashboard/store/dashboard.reducer.ts",
      "src/modules/occurenceBook/occurenceBook.module.ts",
      "src/modules/occurenceBook/occurenceBook.routing.ts",
      "src/modules/occurenceBook/components/ob.component.css",
      "src/modules/occurenceBook/components/ob.component.html",
      "src/modules/occurenceBook/components/ob.component.ts",
      "src/modules/occurenceBook/services/occurenceBook.service.ts",
      "src/modules/occurenceBook/store/occurenceBook.actions.ts",
      "src/modules/occurenceBook/store/occurenceBook.effects.ts",
      "src/modules/occurenceBook/store/occurenceBook.model.ts",
      "src/modules/occurenceBook/store/occurenceBook.reducer.ts"
    ];

    allFileNames.map(file =>
      this.fs.copyTpl(this.templatePath(file), this.destinationPath('public/' + file), {
        ENV_CONFIG: {
          production: false
        }
      })
    );
    //
    // this.fs.copy(
    //   this.templatePath('dummyfile.txt'),
    //   this.destinationPath('dummyfile.txt')
    // );
  }

  install() {
    this.installDependencies();
  }
};
